# Generated by Django 4.1.5 on 2023-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_open'),
        ('customer', '0002_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
