# Generated by Django 4.1.5 on 2023-01-20 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dishes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
